[package]
name = "khan"
version = "0.1.0"
edition = "2021"
description = "Experimental chess engine"
readme = "readme.md"
license = "Zlib"

[dependencies]
bitflags = "1.3.2"
clap = { version = "3.1.17", features = [ "derive" ] }
vampirc-uci = "0.11.1"
